### ISSUE TITLE
Custom loader for APOGEE spectra

### ISSUE THREAD

**Issue by weaverba137** [spacetelescope/specviz#261]
I'm trying to load APOGEE spectrum files (specifically [aspcapStar files](https://data.sdss.org/datamodel/files/APOGEE_REDUX/APRED_VERS/APSTAR_VERS/ASPCAP_VERS/RESULTS_VERS/LOCATION_ID/aspcapStar.html)) into specviz.  These are formatted very differently from SDSS/BOSS "spec" files.  To summarize:

1. Data and WCS headers are in HDU 1 (HDU 0 is empty), which is a 1-d image, not a table column.
2. The data values are arbitrary units; these spectra are pseudo-continuum normalized.
3. Wavelength solution in WCS is Log-linear.
4. Uncertainties are in HDU 2, which is also a 1-d image.
5. The best-fit spectrum is in HDU 3. I'd like to be able to extract that along with the data spectrum.

Here's what I have so far:

```yaml
--- !CustomLoader
name: APOGEE aspcapStar
extension: fits
wcs:
    hdu: 1
dispersion:
#     hdu: 1
#     col: 1
    unit: 'dex(Angstrom)'
data:
    hdu: 1
#     col: 0
#     unit: '1e-17 erg / (Angstrom cm2 s)'
uncertainty:
    hdu: 2
#     col: 2
#     type: 'ivar'
meta:
    author: Benjamin Alan Weaver
```

With this loader, I get an error: `ERROR:root:Incompatible loader for selected data: APOGEE aspcapStar because 'col'`

**Comment by weaverba137** [comment]
PS, here are the WCS headers used in an aspcapStar file:

``` 
CRVAL1  =        4.17900000000 /
CDELT1  =    6.00000000000E-06 /
CRPIX1  =                    1 /
CTYPE1  = 'LOG-LINEAR'         /
DC-FLAG =                    1 /
```

**Comment by weaverba137** [comment]
After I explicitly put a column definition back in:

```yaml
--- !CustomLoader
name: APOGEE aspcapStar
extension: fits
wcs:
    hdu: 1
dispersion:
#     hdu: 1
#     col: 1
    unit: 'dex(Angstrom)'
data:
     hdu: 1
     col: 0
#     unit: '1e-17 erg / (Angstrom cm2 s)'
uncertainty:
     hdu: 2
     col: 0
#     type: 'ivar'
meta:
    author: Benjamin Alan Weaver
```
I got a different error: `ERROR:root:Incompatible loader for selected data: APOGEE aspcapStar because unsupported operand type(s) for *: 'NoneType' and 'DexUnit'`.

**Comment by nmearl** [comment]
Hey @weaverba137. The yaml parser is a bit rigid at the moment, but we're constantly improving it and it's people with interesting data formats that help us make it better.

The first error you're seeing is due to the fact that the parse expects hdu and column information *at the least*. The second error comes because the `dispersion` key doesn't contain hdu or col information, so it's assuming the `dispersion` array is `None`. Thus, it's trying to multiply `None` by the `'dex(Angstrom)'` unit information when generating a `Quantity`.

**Comment by nmearl** [comment]
It's also possible to make a custom loader directly in Python instead of YAML. For reference, take a look at [this example](https://github.com/spacetelescope/specviz/blob/master/specviz/io/loaders/generic_loader.py) of the generic fits loader that currently exists in SpecViz.

To create your own, you can copy that file to your`~/.specviz` directory (where you're placing your `.yaml` files), and it will be picked up by SpecViz.

**Comment by weaverba137** [comment]
Thanx, I tried this:

```yaml
--- !CustomLoader
name: APOGEE aspcapStar
extension: fits
wcs:
    hdu: 1
dispersion:
    hdu: 1
    col: 0
    unit: 'dex(Angstrom)'
data:
    hdu: 1
    col: 0
#    unit: '1e-17 erg / (Angstrom cm2 s)'
uncertainty:
    hdu: 2
    col: 0
    type: 'std'
meta:
    author: Benjamin Alan Weaver
```
and the file "loaded" although nothing was actually plotted.

I will try a Python loader.
